version: '3.4'

services:
  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9808:9808
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
